### PR TITLE
cve fix: upgrade go-git and other dep libs; Lower MaxConcurrentReconc…

### PR DESCRIPTION
**Pull request by xiangjingli**
…iles to 1 for helmRelease controller

* [X] I have taken backward compatibility into consideration.

Two issues are fixed:

- lower MaxConcurrentReconciles to 1 for helmRelease controller.
With the previous 10 concurrent setting, we identified there is OOM killed issue in the footprint assessment test env where the managed cluster is SNO cluster with limited memory. Setting it to 1 stabilized the running of the application-manager pod
https://issues.redhat.com/browse/ACM-8936

- CVE fixes - upgrade go-git lib and other dep pkg
https://issues.redhat.com/browse/ACM-9371
https://issues.redhat.com/browse/ACM-9368

### CODE REVIEW

**Comment by mikeshng** [comment]
@xiangjingli side effect of this change is if there is a helm chart that is taking forever to install (for example: a very long running hook job) then all the other helmrelease will be blocked and unable to reconcile. I am guessing this is why the e2e is timing out?

**Comment by xiangjingli** [comment]
@mikeshng   THX! I increased the MaxConcurrentReconciles to 2 and all the e2e tests passed. 2 may be a better choice so that we have the minimum concurrency reconcile capability while we won't hit OOM too often compared to 10

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Pull request merged**
