### PR TITLE
Refine the presentation

### PR DESCRIPTION
**Pull request by vincent-pli**
I think the new presentation should better matched what it do in that section.

### CODE REVIEW

**Review by mikeshng — APPROVED** [review]
Thanks!

/approve

/lgtm

**Comment by mikeshng** [comment]
@vincent-pli Could you fix your commit with a sign-off please? You can run something like `git commit -s --amend` and then force push again.

**Comment by vincent-pli** [comment]
@mikeshng sorry missing `sign-off`, thanks

**Comment by mikeshng** [comment]
/lgtm

thanks again

**Pull request merged**
