### PR TITLE
Enable Helm for the policy generator

### PR DESCRIPTION
**Pull request by dhaiducek**
ref: https://issues.redhat.com/browse/ACM-9060

* [x] I have taken backward compatibility into consideration.

/cc @mprahl

### CODE REVIEW

**Comment by mikeshng** [comment]
/approve

please feel free to l g t m whenever

**Comment by dhaiducek** [comment]
Thanks @mikeshng! Would you re-run the `Go / test` workflow? I'm not sure why that one would have failed with this change.

**Comment by mikeshng** [comment]
Test seems to ran fine the last time but the report coverage server had issue. Retrying again.

**Review by gparvin — APPROVED** [review]

**Pull request merged**
