### PR TITLE
fix: report failed propagation for failures in preliminary operations

### PR DESCRIPTION
**Pull request by TomerFi**
fixes: https://github.com/stolostron/backlog/issues/26715
backlog issue: https://github.com/stolostron/backlog/issues/25649

### CODE REVIEW

**Comment by TomerFi** [comment]
Looks like this is blocked for #276.

**Review by mikeshng — COMMENTED** [review]
Changes look good to me. @chenz4027 Could you please another look since you are more familiar with the metric part? Thanks.

**Comment by mikeshng** [comment]
> Looks like this is blocked for #276.

`https://github.com/open-cluster-management-io/registration-operator/pull/298`

It seems like e2e will be blocked until this gets merged.

**Pull request merged**
