### PR TITLE
Deploy addon agent via hub

### PR DESCRIPTION
**Pull request by qiujian16**
Signed-off-by: Jian Qiu <jqiu@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
assign @mikeshng

**Review by mikeshng — APPROVED** [review]
/lgtm

This is an amazing PR. It enhances the subscription operator usability with the ocm addon agent deployment. It adds e2e test coverage. It has fixes for an existing race condition problem with manager startup. Thank you once again!

**Pull request merged**
