### PR TITLE
Remove legacy auto gen file that is no longer in use

### PR DESCRIPTION
**Pull request by dhaiducek**
Cherry-pick of:
- https://github.com/open-cluster-management/multicloud-operators-placementrule/pull/119

### CODE REVIEW

**Comment by dhaiducek** [comment]
This should hopefully fix GRC packages trying to pull in the PlacementRule:
```
# open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1
Error: /go/pkg/mod/open-cluster-management.io/multicloud-operators-subscription@v0.5.0/pkg/apis/apps/placementrule/v1/zz_generated.openapi.go:34:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
Error: /go/pkg/mod/open-cluster-management.io/multicloud-operators-subscription@v0.5.0/pkg/apis/apps/placementrule/v1/zz_generated.openapi.go:55:8: cannot use ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
Error: /go/pkg/mod/open-cluster-management.io/multicloud-operators-subscription@v0.5.0/pkg/apis/apps/placementrule/v1/zz_generated.openapi.go:60:8: cannot use ref("open-cluster-management.io/multicloud-operators-subscription/pkg/api...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
Error: /go/pkg/mod/open-cluster-management.io/multicloud-operators-subscription@v0.5.0/pkg/apis/apps/placementrule/v1/zz_generated.openapi.go:65:8: cannot use ref("open-cluster-management.io/multicloud-operators-subscription/pkg/api...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
```
https://github.com/open-cluster-management-io/governance-policy-spec-sync/runs/4587483893?check_suite_focus=true#step:8:118-122

**Comment by mikeshng** [comment]
fossa scan fix PR https://github.com/open-cluster-management-io/multicloud-operators-subscription/pull/61

**Comment by dhaiducek** [comment]
Would someone please re-run these tests? The failure was intermittent as far as I can tell.

**Review by mikeshng — APPROVED** [review]
/lgtm

**Comment by mikeshng** [comment]
Sorry about that we will try to fix the test asap. We think it has to do with GitHub actions performance related. For now lets do just do a few retries and it should go thru.

**Pull request merged**
